// GENERATED then hand-maintained: seeded verbatim from today's live config by
// scripts/seed-mode-folders.mjs (deleted after use), then committed as ordinary source.

import type { CarDef, CarId } from "../../config/types.js";

export const CONQUER_CARS = {
  mirage: {
    id: "mirage",
    name: "Mirage",
    speed: 85,
    accel: 85,
    handling: 85,
    attack: 63,
    hp: 70,
    ramAttack: 55,
    ramDefence: 50,
    brakeDecel: 500,
    weapons: [
      "magmablast",
      "thunderclap",
      "afterburner",
    ],
    basicAttack: "basic-attack-mirage",
    turretMount: {
      x: 0,
      y: 0,
    },
    isActive: true,
  },
  bullseye: {
    id: "bullseye",
    name: "Bullseye",
    speed: 65,
    accel: 45,
    handling: 65,
    attack: 55,
    hp: 65,
    ramAttack: 45,
    ramDefence: 30,
    brakeDecel: 520,
    weapons: [
      "predator",
      "pepperbox",
      "lance",
    ],
    basicAttack: "basic-attack-bullseye",
    turretMount: {
      x: 0,
      y: 0,
    },
    isActive: true,
  },
  bastion: {
    id: "bastion",
    name: "Bastion",
    speed: 50,
    accel: 20,
    handling: 50,
    attack: 42,
    hp: 90,
    ramAttack: 70,
    ramDefence: 90,
    brakeDecel: 430,
    weapons: [
      "thumper",
      "roadblock",
      "wildcharge",
    ],
    basicAttack: "basic-attack-bastion",
    turretMount: {
      x: 0,
      y: 0,
    },
    isActive: true,
  },
  taurus: {
    id: "taurus",
    name: "Taurus",
    speed: 50,
    accel: 20,
    handling: 50,
    attack: 42,
    hp: 90,
    ramAttack: 70,
    ramDefence: 90,
    brakeDecel: 430,
    weapons: [],
    basicAttack: "basic-attack-taurus",
    turretMount: {
      x: 0,
      y: 0,
    },
    isActive: false,
  },
  anvil: {
    id: "anvil",
    name: "Anvil",
    speed: 50,
    accel: 20,
    handling: 50,
    attack: 42,
    hp: 90,
    ramAttack: 70,
    ramDefence: 90,
    brakeDecel: 430,
    weapons: [],
    basicAttack: "basic-attack-anvil",
    turretMount: {
      x: 0,
      y: 0,
    },
    isActive: false,
  },
  prowler: {
    id: "prowler",
    name: "Prowler",
    speed: 85,
    accel: 85,
    handling: 85,
    attack: 63,
    hp: 70,
    ramAttack: 55,
    ramDefence: 50,
    brakeDecel: 500,
    weapons: [],
    basicAttack: "basic-attack-prowler",
    turretMount: {
      x: 0,
      y: 0,
    },
    isActive: false,
  },
  cleaver: {
    id: "cleaver",
    name: "Cleaver",
    speed: 85,
    accel: 85,
    handling: 85,
    attack: 63,
    hp: 70,
    ramAttack: 55,
    ramDefence: 50,
    brakeDecel: 500,
    weapons: [],
    basicAttack: "basic-attack-cleaver",
    turretMount: {
      x: 0,
      y: 0,
    },
    isActive: false,
  },
  skorpios: {
    id: "skorpios",
    name: "Skorpios",
    speed: 65,
    accel: 45,
    handling: 65,
    attack: 55,
    hp: 65,
    ramAttack: 45,
    ramDefence: 30,
    brakeDecel: 520,
    weapons: [],
    basicAttack: "basic-attack-skorpios",
    turretMount: {
      x: 0,
      y: 0,
    },
    isActive: false,
  },
  caprico: {
    id: "caprico",
    name: "Caprico",
    speed: 50,
    accel: 20,
    handling: 50,
    attack: 42,
    hp: 90,
    ramAttack: 70,
    ramDefence: 90,
    brakeDecel: 430,
    weapons: [],
    basicAttack: "basic-attack-caprico",
    turretMount: {
      x: 0,
      y: 0,
    },
    isActive: false,
  },
} as const satisfies Record<CarId, CarDef>;
