// GENERATED then hand-maintained: seeded verbatim from today's live config by
// scripts/seed-mode-folders.mjs (deleted after use), then committed as ordinary source.

import type { WeaponDef, WeaponId } from "../../config/weapon-types.js";

export const BRAWL_WEAPONS = {
  predator: {
    id: "predator",
    kind: "projectile",
    name: "Predator",
    color: "#606060",
    unlocksAt: 1,
    damage: 30,
    damageFrequencyMs: 0,
    speed: 900,
    range: 1800,
    startUpMs: 0,
    cooldownMs: 1000,
    recoveryMs: 0,
    hitbox: {
      shape: "capsule",
      radiusAlong: 19,
      radiusAcross: 6,
    },
    pierce: 0,
    lifetimeMs: 2000,
    homing: {
      acquire: "proximity",
      acquireRadius: 200,
      turnRateDegPerSec: 300,
      durationMs: 2000,
    },
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    pellets: {
      pelletsPerVolley: 1,
      spreadAngleDeg: 0,
    },
  },
  thunderclap: {
    id: "thunderclap",
    kind: "maneuver",
    name: "Thunderclap",
    color: "#3ED1FA",
    unlocksAt: 1,
    damage: 90,
    damageFrequencyMs: 0,
    speed: 1600,
    range: 400,
    startUpMs: 0,
    cooldownMs: 5000,
    recoveryMs: 200,
    maneuver: {
      type: "dash",
    },
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    applies: [
      {
        statusId: "stunned",
        target: "opponents",
        durationMs: 1000,
      },
    ],
  },
  afterburner: {
    id: "afterburner",
    kind: "beam",
    name: "Afterburner",
    color: "#FF9000",
    unlocksAt: 1,
    damage: 49,
    damageFrequencyMs: 500,
    speed: 1100,
    range: 220,
    startUpMs: 0,
    cooldownMs: 13000,
    recoveryMs: 200,
    muzzles: [
      0,
      180,
    ],
    hitbox: {
      shape: "cone",
      angleDeg: 55,
    },
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    attached: true,
    origin: "muzzle",
    lifetimeMs: 2000,
    applies: [
      {
        statusId: "overheated",
        target: "opponents",
        durationMs: 1500,
      },
    ],
  },
  magmablast: {
    id: "magmablast",
    kind: "projectile",
    name: "Magma Blast",
    color: "#FF6000",
    unlocksAt: 1,
    damage: 50,
    damageFrequencyMs: 0,
    speed: 600,
    range: 900,
    startUpMs: 0,
    cooldownMs: 1600,
    recoveryMs: 0,
    hitbox: {
      shape: "circle",
      radius: 12,
    },
    pierce: 0,
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    pellets: {
      pelletsPerVolley: 1,
      spreadAngleDeg: 0,
    },
    explosion: {
      radius: 60,
      damage: 15,
      lingerMs: 2000,
      damageMode: "perEntry",
      applies: [
        {
          statusId: "corroded",
          target: "opponents",
          durationMs: 2000,
        },
      ],
    },
  },
  pepperbox: {
    id: "pepperbox",
    kind: "projectile",
    name: "Pepperbox",
    color: "#C04818",
    unlocksAt: 1,
    damage: 45,
    damageFrequencyMs: 0,
    speed: 800,
    range: 600,
    startUpMs: 0,
    cooldownMs: 1800,
    recoveryMs: 200,
    muzzles: [
      0,
      90,
      180,
      270,
    ],
    hitbox: {
      shape: "ellipse",
      radiusAlong: 9,
      radiusAcross: 3,
    },
    pierce: 0,
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    pellets: {
      pelletsPerVolley: 3,
      spreadAngleDeg: 12,
    },
  },
  lance: {
    id: "lance",
    kind: "beam",
    name: "Lance",
    color: "#F0FF00",
    unlocksAt: 1,
    damage: 43,
    damageFrequencyMs: 500,
    speed: 6000,
    range: 1200,
    startUpMs: 700,
    cooldownMs: 16000,
    recoveryMs: 1000,
    hitbox: {
      shape: "rect",
      width: 57.5,
    },
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    attached: true,
    origin: "muzzle",
    lifetimeMs: 1500,
    holdsDuringFire: true,
  },
  thumper: {
    id: "thumper",
    kind: "projectile",
    name: "Thumper",
    color: "#FFD800",
    unlocksAt: 1,
    damage: 60,
    damageFrequencyMs: 0,
    speed: 450,
    range: 1305,
    startUpMs: 0,
    cooldownMs: 3000,
    recoveryMs: 0,
    hitbox: {
      shape: "capsule",
      radiusAlong: 24,
      radiusAcross: 15,
    },
    pierce: 0,
    bounces: true,
    lifetimeMs: 2900,
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    pellets: {
      pelletsPerVolley: 1,
      spreadAngleDeg: 0,
    },
    applies: [
      {
        statusId: "spiked",
        target: "opponents",
        durationMs: 3000,
      },
    ],
  },
  roadblock: {
    id: "roadblock",
    kind: "projectile",
    name: "Roadblock",
    color: "#D89000",
    unlocksAt: 1,
    damage: 100,
    damageFrequencyMs: 0,
    speed: 600,
    range: 500,
    startUpMs: 0,
    cooldownMs: 6000,
    recoveryMs: 200,
    hitbox: {
      shape: "bar",
      radiusAlong: 6,
      radiusAcross: 60,
    },
    pierce: 4,
    piercesWalls: true,
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    pellets: {
      pelletsPerVolley: 1,
      spreadAngleDeg: 0,
    },
    applies: [
      {
        statusId: "stunned",
        target: "opponents",
        durationMs: 1000,
      },
    ],
  },
  wildcharge: {
    id: "wildcharge",
    kind: "maneuver",
    name: "Wild Charge",
    color: "#F06000",
    unlocksAt: 1,
    damage: 250,
    damageFrequencyMs: 0,
    speed: 0,
    range: 0,
    startUpMs: 0,
    cooldownMs: 20000,
    recoveryMs: 200,
    isUnInterruptable: true,
    maneuver: {
      type: "charge",
      durationMs: 10000,
      slamsStunned: true,
    },
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    applies: [
      {
        statusId: "fortified",
        target: "self",
        durationMs: 10000,
      },
    ],
    impulse: {
      speed: 520,
      direction: "radial",
      spin: 0,
      defenceScaled: false,
      applies: [
        {
          statusId: "reeling",
          durationMs: 1400,
        },
      ],
      onWallImpact: {
        windowMs: 500,
        applies: [
          {
            statusId: "stunned",
            durationMs: 500,
          },
        ],
      },
      retriggerImmunityMs: 600,
    },
  },
  tremor: {
    id: "tremor",
    kind: "beam",
    name: "Tremor",
    color: "#8A6D12",
    unlocksAt: 1,
    damage: 25,
    damageFrequencyMs: 400,
    speed: 492,
    range: 492,
    startUpMs: 0,
    cooldownMs: 15000,
    recoveryMs: 200,
    hitbox: {
      shape: "cone",
      angleDeg: 60,
    },
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    attached: false,
    origin: "muzzle",
    lifetimeMs: 2875,
    applies: [
      {
        statusId: "spiked",
        target: "opponents",
        durationMs: 600,
      },
      {
        statusId: "fortified",
        target: "ownerInside",
        durationMs: 300,
      },
    ],
  },
  "basic-attack-bullseye": {
    kind: "projectile",
    name: "Basic Attack",
    color: "#101014",
    unlocksAt: 1,
    damage: 20,
    damageFrequencyMs: 0,
    speed: 900,
    range: 960,
    startUpMs: 0,
    cooldownMs: 800,
    recoveryMs: 0,
    hitbox: {
      shape: "circle",
      radius: 12,
    },
    pierce: 0,
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    pellets: {
      pelletsPerVolley: 1,
      spreadAngleDeg: 0,
    },
    turret: {
      additionalOffset: 0,
    },
    id: "basic-attack-bullseye",
  },
  "basic-attack-mirage": {
    kind: "projectile",
    name: "Basic Attack",
    color: "#101014",
    unlocksAt: 1,
    damage: 20,
    damageFrequencyMs: 0,
    speed: 900,
    range: 960,
    startUpMs: 0,
    cooldownMs: 800,
    recoveryMs: 0,
    hitbox: {
      shape: "circle",
      radius: 12,
    },
    pierce: 0,
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    pellets: {
      pelletsPerVolley: 1,
      spreadAngleDeg: 0,
    },
    turret: {
      additionalOffset: 0,
    },
    id: "basic-attack-mirage",
  },
  "basic-attack-bastion": {
    kind: "projectile",
    name: "Basic Attack",
    color: "#101014",
    unlocksAt: 1,
    damage: 20,
    damageFrequencyMs: 0,
    speed: 900,
    range: 960,
    startUpMs: 0,
    cooldownMs: 800,
    recoveryMs: 0,
    hitbox: {
      shape: "circle",
      radius: 12,
    },
    pierce: 0,
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    pellets: {
      pelletsPerVolley: 1,
      spreadAngleDeg: 0,
    },
    turret: {
      additionalOffset: 0,
    },
    id: "basic-attack-bastion",
  },
  "basic-attack-taurus": {
    kind: "projectile",
    name: "Basic Attack",
    color: "#101014",
    unlocksAt: 1,
    damage: 20,
    damageFrequencyMs: 0,
    speed: 900,
    range: 960,
    startUpMs: 0,
    cooldownMs: 800,
    recoveryMs: 0,
    hitbox: {
      shape: "circle",
      radius: 12,
    },
    pierce: 0,
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    pellets: {
      pelletsPerVolley: 1,
      spreadAngleDeg: 0,
    },
    turret: {
      additionalOffset: 0,
    },
    id: "basic-attack-taurus",
  },
  "basic-attack-anvil": {
    kind: "projectile",
    name: "Basic Attack",
    color: "#101014",
    unlocksAt: 1,
    damage: 20,
    damageFrequencyMs: 0,
    speed: 900,
    range: 960,
    startUpMs: 0,
    cooldownMs: 800,
    recoveryMs: 0,
    hitbox: {
      shape: "circle",
      radius: 12,
    },
    pierce: 0,
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    pellets: {
      pelletsPerVolley: 1,
      spreadAngleDeg: 0,
    },
    turret: {
      additionalOffset: 0,
    },
    id: "basic-attack-anvil",
  },
  "basic-attack-prowler": {
    kind: "projectile",
    name: "Basic Attack",
    color: "#101014",
    unlocksAt: 1,
    damage: 20,
    damageFrequencyMs: 0,
    speed: 900,
    range: 960,
    startUpMs: 0,
    cooldownMs: 800,
    recoveryMs: 0,
    hitbox: {
      shape: "circle",
      radius: 12,
    },
    pierce: 0,
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    pellets: {
      pelletsPerVolley: 1,
      spreadAngleDeg: 0,
    },
    turret: {
      additionalOffset: 0,
    },
    id: "basic-attack-prowler",
  },
  "basic-attack-cleaver": {
    kind: "projectile",
    name: "Basic Attack",
    color: "#101014",
    unlocksAt: 1,
    damage: 20,
    damageFrequencyMs: 0,
    speed: 900,
    range: 960,
    startUpMs: 0,
    cooldownMs: 800,
    recoveryMs: 0,
    hitbox: {
      shape: "circle",
      radius: 12,
    },
    pierce: 0,
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    pellets: {
      pelletsPerVolley: 1,
      spreadAngleDeg: 0,
    },
    turret: {
      additionalOffset: 0,
    },
    id: "basic-attack-cleaver",
  },
  "basic-attack-skorpios": {
    kind: "projectile",
    name: "Basic Attack",
    color: "#101014",
    unlocksAt: 1,
    damage: 20,
    damageFrequencyMs: 0,
    speed: 900,
    range: 960,
    startUpMs: 0,
    cooldownMs: 800,
    recoveryMs: 0,
    hitbox: {
      shape: "circle",
      radius: 12,
    },
    pierce: 0,
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    pellets: {
      pelletsPerVolley: 1,
      spreadAngleDeg: 0,
    },
    turret: {
      additionalOffset: 0,
    },
    id: "basic-attack-skorpios",
  },
  "basic-attack-caprico": {
    kind: "projectile",
    name: "Basic Attack",
    color: "#101014",
    unlocksAt: 1,
    damage: 20,
    damageFrequencyMs: 0,
    speed: 900,
    range: 960,
    startUpMs: 0,
    cooldownMs: 800,
    recoveryMs: 0,
    hitbox: {
      shape: "circle",
      radius: 12,
    },
    pierce: 0,
    volley: {
      volleys: 1,
      volleyIntervalMs: 0,
    },
    pellets: {
      pelletsPerVolley: 1,
      spreadAngleDeg: 0,
    },
    turret: {
      additionalOffset: 0,
    },
    id: "basic-attack-caprico",
  },
} as const satisfies Record<WeaponId, WeaponDef>;
