/**
 * The release's `.env`: what goes in it, how a `--port` argument reaches it, and the URLs that
 * follow from it.
 *
 * Separate from `build-release.mjs` on purpose. That module statically imports built shared, so
 * importing it costs a `packages/shared/dist` that may not exist yet — and `install-build.mjs`
 * needs to parse `--port` *before* it builds anything, so that a typo'd port fails in a second
 * alongside a typo'd path. Nothing here reads shared, so both scripts can import it at load time.
 */

/**
 * One line of an env file: a `key=value` assignment, or a raw passthrough (comment, blank line).
 *
 * Comments are kept as lines rather than discarded because the shipped `.env` is where the LAN
 * host's configuration is *documented*, not just declared — an edit that dropped its prose would
 * leave them a bare list of keys with no hint what any of them do.
 */
function parseEnvLines(text) {
  return text.split(/\r?\n/).map((raw) => {
    const match = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$/.exec(raw);
    return match ? { key: match[1], value: match[2].trim() } : { raw };
  });
}

/**
 * The port a release gets when the build was not told otherwise.
 *
 * Must stay in step with `getPort()` in `packages/server/src/mode.ts`. It is repeated rather than
 * imported because that is TypeScript the build scripts do not compile, and a release whose `.env`
 * disagreed with the server's own fallback would send every player to a closed port.
 *
 * Deliberately the ordinary default and not something friendlier like 80: a port below 1024 is
 * privileged on macOS and Linux, so baking one in would make the default release fail to start on
 * two of three platforms. A host who wants one asks for it — `--port 80`.
 */
export const DEFAULT_RELEASE_PORT = 2567;

/** Ports TCP can express. 0 is excluded: "any free port" is meaningless for a URL players type. */
export function parsePortArg(argv) {
  const index = argv.findIndex((arg) => arg === "--port" || arg.startsWith("--port="));
  if (index === -1) return { port: undefined };

  const arg = argv[index];
  const raw = arg.startsWith("--port=") ? arg.slice("--port=".length) : argv[index + 1];
  if (raw === undefined || raw.startsWith("--")) {
    return { error: "--port needs a number, e.g. --port 80." };
  }

  const port = Number(raw);
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    return { error: `--port must be a whole number from 1 to 65535, not "${raw}".` };
  }
  return { port };
}

/**
 * The `.env` the release ships, generated rather than copied from a committed template.
 *
 * A real `.env` and not a `.env.example` the host has to notice and rename: `start.bat` / `start.sh`
 * cd to this folder, so it is exactly where the server's `dotenv/config` looks. The commented knobs
 * are the point of writing a file at all when the port is the default — it is the one place a LAN
 * host can see what is tunable without reading the source.
 */
export function releaseEnvFile(port) {
  return `# Configuration for this LAN server. Edit and restart — no rebuild needed.
#
# Generated by \`npm run build:release\`. To bake a different port into a future release, build it
# with \`npm run build:release -- --port <n>\` rather than editing this file afterwards.

DEPLOY_MODE=lan

# The port the server listens on, and so the one players type. Above 1024 anywhere; 80 lets them
# reach the game by name alone (http://gamepc) but is privileged on macOS and Linux.
PORT=${port}

# Blank means "use the built-in default".
TICK_RATE_HZ=
SIM_LATENCY_MS=
SIM_JITTER_MS=
`;
}

/**
 * Rewrite `PORT` in an existing env file, in place, leaving every other key and comment as it was.
 *
 * This is what lets `install-build --port` reach a folder that already has a hand-edited `.env`:
 * the host asked for a port explicitly, so it wins, but nothing else they set is collateral.
 * A file with no `PORT` line at all gets one appended rather than being silently ignored.
 */
export function setEnvPort(envText, port) {
  let replaced = false;
  const lines = parseEnvLines(envText).map((line) => {
    if (line.key !== "PORT") return line;
    replaced = true;
    return { key: "PORT", value: String(port) };
  });
  if (!replaced) {
    while (lines.length > 0 && lines.at(-1).key === undefined && !lines.at(-1).raw.trim()) {
      lines.pop();
    }
    if (lines.length > 0) lines.push({ raw: "" });
    lines.push({ key: "PORT", value: String(port) });
  }
  const body = lines
    .map((line) => (line.key === undefined ? line.raw : `${line.key}=${line.value}`))
    .join("\n")
    .replace(/\n+$/, "");
  return `${body}\n`;
}

/**
 * The port an env file actually selects, so a README or a closing message can print a URL that
 * works. Last assignment wins, matching how dotenv folds a file into one object.
 */
export function releasePort(envText, fallback = DEFAULT_RELEASE_PORT) {
  let port = fallback;
  for (const line of parseEnvLines(envText)) {
    if (line.key !== "PORT") continue;
    const n = Number(line.value);
    if (Number.isFinite(n) && n > 0) port = n;
  }
  return port;
}

/** `http://host` on port 80, `http://host:port` anywhere else — a URL a player can actually type. */
export function releaseOrigin(host, port) {
  return port === 80 ? `http://${host}` : `http://${host}:${port}`;
}

export function releaseReadme(port) {
  const privileged = port < 1024;
  return `# Motor Combat MOBA (LAN)

Requires Node.js 20 or newer.

1. Double-click \`start.bat\` (Windows) or run \`./start.sh\` (macOS/Linux).
2. The first launch installs dependencies, then starts the server.
3. Open ${releaseOrigin("localhost", port)} on this machine.
4. Share ${releaseOrigin("<LAN-IP>", port)} with other players on the same network.

The port is \`PORT\` in \`.env\`, next to \`start.bat\`. Change it there and restart.
${
  privileged
    ? `
Port ${port} is a privileged port. Windows binds it without admin rights, but macOS and Linux do
not: run \`sudo setcap 'cap_net_bind_service=+ep' $(which node)\` once, or set a port above 1024 in
\`.env\`. If the port is already taken the server exits on startup — on Windows that is usually IIS
(\`net stop http /y\`).
`
    : ""
}`;
}
